language: java   

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

script:
 - mvn package sonar:sonar -Dsonar.organization=sbouchet-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=b2756b8513cf9bd5edbc26fc684864fb17038846
